name: Sensor Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: raspberrypi-1
            host: SSH_HOST_PI_1
            profile: windtunnel
            logs: tachometer

          - name: raspberrypi-2
            host: SSH_HOST_PI_2
            profile: windtunnel-2
            logs: pitot-static barometer thermometer status

          - name: raspberrypi-3
            host: SSH_HOST_PI_3
            profile: windtunnel-3
            logs: pitot-static barometer thermometer status

          - name: raspberrypi-4
            host: SSH_HOST_PI_4
            profile: windtunnel-4
            logs: tachometer

    steps:
      - name: Deploy sensor containers
        uses: appleboy/ssh-action@master
        with:
          # Tailscale server
          proxy_host: ${{ secrets.SSH_HOST }}
          proxy_username: ${{ secrets.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_port: 22

          # Raspberry Pi
          host: ${{ secrets[matrix.host] }}
          username: ${{ secrets.SSH_USERNAME_PI }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PI }}
          port: 22

          script: |
            cd ~/Projects/windtunnel/microcontrollers

            # Pull latest code
            git pull

            # Build containers
            docker compose --profile "${{ matrix.profile }}" build

            # Stop all current containers
            docker compose --profile "*" down

            # Start containers
            docker compose --profile "${{ matrix.profile }}" up -d

            # Watch sensor logs for 5 minutes
            timeout 5m docker compose logs -f ${{ matrix.logs }} || true